import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { renderStatus } from "../src/commands/status.js";
import { findEntry, parseOneshot, readLibrary, readLibraryIssues } from "../src/core/library.js";
import { clipboardCommand, copyToClipboard } from "../src/ui/clipboard.js";

// --- fixtures ----------------------------------------------------------------

const tmpDirs: string[] = [];
function tmpHome(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cch-lib-"));
  tmpDirs.push(dir);
  return dir;
}

afterEach(() => {
  while (tmpDirs.length) {
    const d = tmpDirs.pop();
    if (d) fs.rmSync(d, { recursive: true, force: true });
  }
});

function writeEntry(
  home: string,
  slug: string,
  overrides: Record<string, unknown> = {},
  oneshotBody = "Do the thing well.",
): void {
  const dir = path.join(home, "library", slug);
  fs.mkdirSync(dir, { recursive: true });
  const sources = {
    slug,
    title: `Title of ${slug}`,
    members: ["a.md"],
    sessionIds: ["sid-a"],
    preferences: [],
    outcome_summary: "1 completed",
    domains: ["testing"],
    confidence: "high",
    authored_at: "2026-07-01T00:00:00.000Z",
    model: null,
    prompt_version: 1,
    tool_version: "0.1.0",
    generation: "g1",
    ...overrides,
  };
  fs.writeFileSync(path.join(dir, "sources.json"), JSON.stringify(sources));
  fs.writeFileSync(
    path.join(dir, `${slug}.oneshot.md`),
    `<!--\n  generated by cc-hindsight v0.1.0\n-->\n\n# ${sources.title}\n\n${oneshotBody}\n`,
  );
}

// --- clipboard ---------------------------------------------------------------

describe("clipboardCommand", () => {
  it("selects the platform tool", () => {
    expect(clipboardCommand("darwin", {})).toEqual({ cmd: "pbcopy", args: [] });
    expect(clipboardCommand("win32", {})).toEqual({ cmd: "clip", args: [] });
    expect(clipboardCommand("linux", { WAYLAND_DISPLAY: "wayland-0" })).toEqual({
      cmd: "wl-copy",
      args: [],
    });
    expect(clipboardCommand("linux", {})).toEqual({
      cmd: "xclip",
      args: ["-selection", "clipboard"],
    });
  });
});

describe("copyToClipboard", () => {
  it("pipes text to the selected tool via the injected spawn", async () => {
    let captured: { cmd: string; input: string } | undefined;
    const result = await copyToClipboard("the prompt", {
      platform: "darwin",
      spawn: async (cmd, _args, input) => {
        captured = { cmd, input };
        return { code: 0 };
      },
    });
    expect(result).toEqual({ ok: true, tool: "pbcopy" });
    expect(captured).toEqual({ cmd: "pbcopy", input: "the prompt" });
  });

  it("gives up on a clipboard tool that never exits", async () => {
    // A clipboard tool can hang instead of failing: `xclip` with no X display
    // holds the selection forever, and the copy offer is the LAST thing a
    // distill run does, so the whole run appears to hang after its work is
    // already finished and saved. Bound it rather than waiting forever.
    const t0 = Date.now();
    const result = await copyToClipboard("x", {
      platform: "linux",
      env: {},
      timeoutMs: 150,
      spawn: (_cmd, _args, _input) => new Promise(() => {}), // never settles
    });
    expect(Date.now() - t0).toBeLessThan(3_000);
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/timed out/i);
  }, 20_000);

  it("reports failure with the tool name and error", async () => {
    const result = await copyToClipboard("x", {
      platform: "linux",
      env: {},
      spawn: async () => ({ code: null, error: "spawn xclip ENOENT" }),
    });
    expect(result.ok).toBe(false);
    expect(result.tool).toBe("xclip");
    expect(result.error).toContain("ENOENT");
  });
});

// --- library reading -----------------------------------------------------------

describe("readLibrary / findEntry / parseOneshot", () => {
  it("reads entries newest-first and finds by slug", () => {
    const home = tmpHome();
    writeEntry(home, "older-task-here", { authored_at: "2026-06-01T00:00:00.000Z" });
    writeEntry(home, "newer-task-here", { authored_at: "2026-07-02T00:00:00.000Z" });
    const entries = readLibrary(home);
    expect(entries.map((e) => e.slug)).toEqual(["newer-task-here", "older-task-here"]);
    expect(findEntry(home, "older-task-here")?.sources.title).toBe("Title of older-task-here");
    expect(findEntry(home, "ghost")).toBeNull();
  });

  it("returns empty for a missing library and skips broken entries", () => {
    const home = tmpHome();
    expect(readLibrary(home)).toEqual([]);
    fs.mkdirSync(path.join(home, "library", "broken-entry-dir"), { recursive: true });
    expect(readLibrary(home)).toEqual([]);
  });

  it("skips a schema-invalid sources.json and reports it", () => {
    const home = tmpHome();
    writeEntry(home, "good-entry-here");
    // A structurally broken sources.json (missing the required slug): skipped.
    const badDir = path.join(home, "library", "bad-entry-here");
    fs.mkdirSync(badDir, { recursive: true });
    fs.writeFileSync(path.join(badDir, "sources.json"), JSON.stringify({ notASourcesFile: true }));
    // Non-JSON entry.
    const junkDir = path.join(home, "library", "junk-entry-here");
    fs.mkdirSync(junkDir, { recursive: true });
    fs.writeFileSync(path.join(junkDir, "sources.json"), "{ not json");

    const entries = readLibrary(home);
    expect(entries.map((e) => e.slug)).toEqual(["good-entry-here"]);

    const issues = readLibraryIssues(home);
    expect(issues.map((i) => i.slug)).toEqual(["bad-entry-here", "junk-entry-here"]);
    expect(issues.find((i) => i.slug === "junk-entry-here")?.reason).toContain("not valid JSON");
  });

  it("tolerates an odd confidence value without dropping the entry or crashing", () => {
    const home = tmpHome();
    // Hand-edited confidence outside the enum: .catch keeps the entry usable.
    writeEntry(home, "odd-confidence-here", { confidence: "SUPER-HIGH" });
    const entries = readLibrary(home);
    expect(entries.map((e) => e.slug)).toEqual(["odd-confidence-here"]);
    // Coerced to a safe enum value so downstream color lookups never crash.
    expect(["high", "medium", "low"]).toContain(entries[0]?.sources.confidence);
  });

  it("parses a oneshot into provenance, title, and paste-able body", () => {
    const content = `<!--\n  generated by cc-hindsight v0.1.0\n-->\n\n# The Title\n\nLine one.\n\nLine two.\n`;
    const parsed = parseOneshot(content);
    expect(parsed.provenance).toContain("generated by cc-hindsight");
    expect(parsed.title).toBe("The Title");
    expect(parsed.body).toBe("Line one.\n\nLine two.");
    // Body never contains the provenance comment or the title heading:
    expect(parsed.body).not.toContain("<!--");
    expect(parsed.body).not.toContain("# The Title");
  });

  it("tolerates a oneshot without provenance or title", () => {
    expect(parseOneshot("just a prompt")).toEqual({
      provenance: null,
      title: null,
      body: "just a prompt",
    });
  });
});

// --- status funnel ---------------------------------------------------------------

describe("renderStatus", () => {
  function strip(s: string): string {
    // biome-ignore lint/suspicious/noControlCharactersInRegex: stripping ANSI codes
    return s.replace(/\u001b\[[0-9;]*m/g, "");
  }

  it("renders the early funnel with hints before anything is distilled", () => {
    const home = tmpHome();
    const out = strip(
      renderStatus({ home, claudeDir: path.join(home, "no-claude"), source: "claude" }),
    );
    expect(out).toContain("discovered  0 session(s)");
    expect(out).toContain("exported    0 session(s)");
    expect(out).toContain("clustered   —");
    expect(out).toContain("cc-hindsight export");
  });

  it("shows the full funnel with per-task marks, skips, and orphans", () => {
    const home = tmpHome();
    fs.mkdirSync(path.join(home, "exports"), { recursive: true });
    fs.mkdirSync(path.join(home, "distill"), { recursive: true });
    fs.writeFileSync(
      path.join(home, "exports", "manifest.json"),
      JSON.stringify([{ export: "a.md" }, { export: "b.md" }, { export: "c.md" }]),
    );
    const digest = (outcome: string) => ({
      goal: "g",
      deliverable: "d",
      domain: "x",
      keywords: [],
      outcome,
    });
    fs.writeFileSync(
      path.join(home, "distill", "digests.json"),
      JSON.stringify({
        generation: "g2",
        prompt_version: 1,
        digests: {
          "a.md": digest("completed"),
          "b.md": digest("abandoned"),
          "c.md": digest("completed"),
        },
      }),
    );
    fs.writeFileSync(
      path.join(home, "distill", "tasks.json"),
      JSON.stringify({
        generation: "g2",
        prompt_version: 1,
        tasks: [
          { slug: "authored-task-here", title: "t", rationale: "r", members: ["a.md"] },
          { slug: "doomed-task-here", title: "t", rationale: "r", members: ["b.md"] },
          { slug: "pending-task-here", title: "t", rationale: "r", members: ["c.md"] },
        ],
        misc: [],
      }),
    );
    writeEntry(home, "authored-task-here", { generation: "g2" });
    writeEntry(home, "orphaned-task-here", { generation: "g1" }); // stale generation

    const out = strip(
      renderStatus({ home, claudeDir: path.join(home, "no-claude"), source: "claude" }),
    );
    expect(out).toContain("exported    3 session(s)");
    expect(out).toContain("digested    3 session(s)");
    expect(out).toContain("clustered   3 task(s), 0 in misc");
    expect(out).toContain("authored    1 of 3 task(s)");
    expect(out).toContain("✓ authored-task-here");
    expect(out).toContain("· doomed-task-here skipped (no successful sessions: 1 abandoned)");
    expect(out).toContain("· pending-task-here pending");
    expect(out).toContain("1 orphaned library entry");
    expect(out).toContain("⚠ orphaned-task-here (generation g1)");
  });

  it("flags stale digest-checkpoint keys whose session left the manifest (hygiene)", () => {
    const home = tmpHome();
    fs.mkdirSync(path.join(home, "exports"), { recursive: true });
    fs.mkdirSync(path.join(home, "distill"), { recursive: true });
    fs.writeFileSync(
      path.join(home, "exports", "manifest.json"),
      JSON.stringify([{ export: "a.md" }]),
    );
    const digest = { goal: "g", deliverable: "d", domain: "x", keywords: [], outcome: "completed" };
    fs.writeFileSync(
      path.join(home, "distill", "digests.json"),
      JSON.stringify({
        generation: "g2",
        prompt_version: 1,
        digests: { "a.md": digest, "ghost.md": digest },
      }),
    );
    const out = strip(
      renderStatus({ home, claudeDir: path.join(home, "no-claude"), source: "claude" }),
    );
    expect(out).toContain("1 digested session(s) no longer in the manifest");
    expect(out).toContain("⚠ ghost.md");
  });

  it("flags a same-generation zombie (slug dropped by re-clustering) as orphan", () => {
    const home = tmpHome();
    fs.mkdirSync(path.join(home, "distill"), { recursive: true });
    fs.writeFileSync(
      path.join(home, "distill", "digests.json"),
      JSON.stringify({
        generation: "g2",
        prompt_version: 1,
        digests: {
          "a.md": { goal: "g", deliverable: "d", domain: "x", keywords: [], outcome: "completed" },
        },
      }),
    );
    // Current clustering (g2) has ONE task: kept-task-here.
    fs.writeFileSync(
      path.join(home, "distill", "tasks.json"),
      JSON.stringify({
        generation: "g2",
        prompt_version: 1,
        tasks: [{ slug: "kept-task-here", title: "t", rationale: "r", members: ["a.md"] }],
        misc: [],
      }),
    );
    // Library has the kept task AND a zombie from a prior clustering — SAME
    // generation g2 (incremental re-cluster mints no new id), slug no longer in
    // tasks.json. A generation-only orphan check would miss it entirely.
    writeEntry(home, "kept-task-here", { generation: "g2" });
    writeEntry(home, "merged-away-task", { generation: "g2" });

    const out = strip(
      renderStatus({ home, claudeDir: path.join(home, "no-claude"), source: "claude" }),
    );
    // Zombie is NOT counted as authored (1 of 1, not 2 of 1).
    expect(out).toContain("authored    1 of 1 task(s)");
    expect(out).toContain("✓ kept-task-here");
    // ...and IS flagged as an orphan despite the matching generation.
    expect(out).toContain("1 orphaned library entry");
    expect(out).toContain("⚠ merged-away-task");
  });
});

// ---- status: dual-store discovered breakdown --------------------------------

describe("renderStatus — per-source discovered breakdown", () => {
  const FIXTURES = path.join(import.meta.dirname, "fixtures");

  it("shows (N claude, M kiro) when both stores are active, plus the orphan-history note", () => {
    const home = tmpHome();
    const out = renderStatus({
      home,
      claudeDir: path.join(FIXTURES, "export-home"),
      kiroDir: path.join(FIXTURES, "kiro-home"),
      source: "auto",
    });
    // export-home holds 4 claude sessions (alpha + beta); kiro-home holds 5 transcripts.
    expect(out).toContain("discovered");
    expect(out).toContain("(4 claude, 5 kiro)");
    // The orphan .history in kiro-home is surfaced here too.
    expect(out).toContain("1 kiro session(s) whose transcript is gone");
  });

  it("shows no breakdown when a single store is active", () => {
    const home = tmpHome();
    const out = renderStatus({
      home,
      claudeDir: path.join(FIXTURES, "export-home"),
      kiroDir: path.join(FIXTURES, "does-not-exist"),
      source: "auto",
    });
    expect(out).not.toContain("claude,");
    expect(out).not.toContain("kiro)");
  });
});
